version: '3.8'

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ../
      dockerfile: docker/dev.Dockerfile
    env_file:
      - ../.env
    ports:
      - 5173:5173
    volumes:
      - ../package.json:/frontend/package.json
      - ../package-lock.json:/frontend/package-lock.json
      - ../src/:/frontend/src/
      - ../public/:/frontend/public/
