services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ../
      dockerfile: docker/prod.Dockerfile
    env_file:
      - ../.env
    ports:
      - 5173:5173
