export const documentationContent: {
  [key: string]: JSX.Element;
} = {
  api: (
    <div>
      <h2 className='text-2xl font-semibold mb-4'>API Integration Guide</h2>
      <p className='text-gray-700'>
        Learn how to integrate Canceralyze's API with your system for seamless cancer detection and
        reporting.
      </p>
    </div>
  ),
  model: (
    <div>
      <h2 className='text-2xl font-semibold mb-4'>Model Training and Accuracy</h2>
      <p className='text-gray-700'>
        Details on the training process, dataset specifications, and accuracy of the Canceralyze
        model.
      </p>
    </div>
  ),
  security: (
    <div>
      <h2 className='text-2xl font-semibold mb-4'>Data Security and Privacy</h2>
      <p className='text-gray-700'>
        Information about how Canceralyze ensures data security and compliance with privacy
        regulations.
      </p>
    </div>
  ),
  bestPractices: (
    <div>
      <h2 className='text-2xl font-semibold mb-4'>Best Practices for Data Input</h2>
      <p className='text-gray-700'>
        Guidelines for preparing and inputting data for accurate cancer detection results.
      </p>
    </div>
  ),
  outputs: (
    <div>
      <h2 className='text-2xl font-semibold mb-4'>How to Handle Outputs and Interpret Results</h2>
      <p className='text-gray-700'>
        Learn how to interpret the results generated by Canceralyze and the best ways to handle
        different output formats.
      </p>
    </div>
  ),
};
