version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    image: backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
