name: format

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Black
        id: pip
        run: pip install -r <(grep "black" requirements.txt)

      - name: Check formatting
        id: black
        run: black --check --exclude '^.+/migrations/[^/]+.py$' .
