# Generated by Django 5.0.2 on 2024-09-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="breastcancer",
            name="mri",
            field=models.ImageField(blank=True, null=True, upload_to="cancer/breast"),
        ),
    ]
