# Generated by Django 5.0.2 on 2024-09-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0002_breastcancer_mri"),
    ]

    operations = [
        migrations.AddField(
            model_name="braincancer",
            name="mri",
            field=models.ImageField(blank=True, null=True, upload_to="cancer/brain"),
        ),
    ]
