# Generated by Django 5.0.2 on 2024-09-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0003_braincancer_mri"),
    ]

    operations = [
        migrations.AddField(
            model_name="braincancerreport",
            name="status",
            field=models.CharField(
                choices=[("PROCESSING", "processing"), ("COMPLETE", "complete")],
                default="PROCESSING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="breastcancerreport",
            name="status",
            field=models.CharField(
                choices=[("PROCESSING", "processing"), ("COMPLETE", "complete")],
                default="PROCESSING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lungcancerreport",
            name="status",
            field=models.CharField(
                choices=[("PROCESSING", "processing"), ("COMPLETE", "complete")],
                default="PROCESSING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="skincancerreport",
            name="status",
            field=models.CharField(
                choices=[("PROCESSING", "processing"), ("COMPLETE", "complete")],
                default="PROCESSING",
                max_length=20,
            ),
        ),
    ]
