# Generated by Django 5.0.2 on 2024-09-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0007_patient_email_patient_medical_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="patients"),
        ),
    ]
