# Generated by Django 5.0.2 on 2024-09-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0008_patient_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="lungcancerreport",
            name="predicted_label",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lungcancerreport",
            name="probs",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="lungcancerreport",
            name="result_image",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="lungcancerreport",
            name="stats_image",
            field=models.URLField(null=True),
        ),
    ]
