# Generated by Django 5.0.2 on 2024-09-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0010_breastcancerreport_result_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="braincancer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="breastcancer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="lungcancer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="skincancer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="braincancer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="breastcancer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="lungcancer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="skincancer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
