# Generated by Django 5.0.2 on 2024-09-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cancer",
            "0011_alter_braincancer_options_alter_breastcancer_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lungcancerreport",
            name="max_prob",
            field=models.FloatField(null=True),
        ),
    ]
