# Generated by Django 5.0.2 on 2024-09-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0012_lungcancerreport_max_prob"),
    ]

    operations = [
        migrations.AddField(
            model_name="breastcancerreport",
            name="segmented_image",
            field=models.URLField(null=True),
        ),
    ]
