# Generated by Django 5.0.2 on 2024-09-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0013_breastcancerreport_segmented_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.EmailField(max_length=254)),
                ("message", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
