# Generated by Django 5.0.2 on 2024-10-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0014_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="summary",
            field=models.TextField(null=True),
        ),
    ]
