# Generated by Django 5.0.2 on 2024-10-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0015_patient_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="braincancerreport",
            name="segmented_image",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="lungcancerreport",
            name="segmented_image",
            field=models.URLField(null=True),
        ),
    ]
