# Generated by Django 5.0.2 on 2024-10-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0016_braincancerreport_segmented_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("author", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name_plural": "Case Studies",
            },
        ),
    ]
