# Generated by Django 5.0.2 on 2024-10-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0018_breastcancerreport_max_prob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="braincancer",
            name="comments",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="breastcancer",
            name="comments",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="lungcancer",
            name="comments",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="skincancer",
            name="comments",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="Genome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("comments", models.TextField(null=True)),
                (
                    "vcf",
                    models.FileField(blank=True, null=True, upload_to="cancer/genome"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cancer.patient"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GenomeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "processing"),
                            ("COMPLETE", "complete"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                ("output", models.TextField(null=True)),
                (
                    "cancer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="cancer.genome",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
