# Generated by Django 5.0.2 on 2024-10-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0019_braincancer_comments_breastcancer_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skincancer",
            name="mri",
            field=models.ImageField(blank=True, null=True, upload_to="cancer/skin"),
        ),
        migrations.AddField(
            model_name="skincancerreport",
            name="max_prob",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="skincancerreport",
            name="predicted_label",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="skincancerreport",
            name="probs",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="skincancerreport",
            name="result_image",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="skincancerreport",
            name="segmented_image",
            field=models.URLField(null=True),
        ),
    ]
