# Generated by Django 5.0.2 on 2024-10-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cancer", "0021_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
